library(ggplot2)
library(ggpubr)

#This code was used to produce the figures for the bioarchives paper
#Function of the bacteriophage P2 baseplate central spike Apex domain in the infection process

#I am the first author of this publication and I am the author of this R code

#The data to make these plots has not been published to the public therefore all
#names for files have been altered and the data files will not be included here

#The publication of this code does not interfere with the publication of the paper
#Therefore, I am publishing this code to my portfolio

#To view the figures generated by this code
#Use the following link
#https://www.biorxiv.org/content/10.1101/2023.02.25.529910v1.full

#Each set of code with be matched with the figure panel that the code produced

#Figure 3.c: Generate for Circular Dichorism data
#Circular Dichorism is a way of determining the secondary structure of a protein
#Read data file as CD
CD <- read.csv("Example-1.csv")

#Set Samples for Circular Dichorism data
Sample <- CD$Sample

#Set variable for wavelength that the measurements were taken
nm <- CD$nm

#Set variable for the mdeg that changed based on the secondary structure
mdeg <- CD$mdeg

#Making the data frame for the CD measurements
df <- data.frame(Sample, nm, mdeg)

#Assigning the levels for the data frame
#Buffer is no sample added, gpV-WT is the wild type protein, gpV-AA, gpV-FF, and gpV-Del are mutant proteins of gpV-WT 
df$Sample <- factor(df$Sample, levels = c('Buffer', 'gpV-WT', 'gpV-AA', 'gpV-FF', 'gpV-Del'))

#Making the line plot of the CD measurements with each sample being color coded.
#Adjusted the line and individual data points to the desired appearance
p <- ggplot(df, aes(x=nm, y=mdeg, group=Sample)) +
  geom_line(aes(color=Sample)) +
  geom_point(size = 1, aes(color=Sample)) +
  scale_color_manual(values = c("Buffer" = 'black', 'gpV-WT' = 'blue', 'gpV-AA' = 'red', 'gpV-FF' = 'green', 'gpV-Del' = 'purple')) +
  theme_classic() +
  theme(legend.justification =  'top') +
  theme(text = element_text(size = 25)) +
  ylim(-10, 10) +
  xlab("nm") + ylab("mdeg")
p + theme(legend.title = element_blank())

#Figure 3.d: generate for Protein Thermal Shift
#Protein Thermal Shift is a way of determining the thermal stability of a protein

#Read data file as PTS
PTS <- read.csv("Example-2.csv")

#Set Samples for Protein Thermal Shift data
Sample <- PTS$Sample

#Set variable for recorded temperature 
Temp <-PTS$Temp

#Set variable for the measured fluorescent signal data of the thermal stability of the protein samples
Signal <- PTS$Signal

#Making the data frame for the Protein Thermal Shift
df1 <- data.frame(Sample, Temp, Signal)

#Assigning the levels for the data frame
#Buffer is no sample added, gpV-WT is the wild type protein, gpV-AA, gpV-FF, and gpV-Del are mutant proteins of gpV-WT 
df1$Sample <- factor(df1$Sample, levels = c('Buffer + Dye', 'gpV-WT', 'gpV-AA', 'gpV-FF', 'gpV-Del'))

#Making the line plot of the Protein Thermal Shift measurements with each sample being color coded.
#Adjusted the line and individual data points to the desired appearance
p1 <- ggplot(df1, aes(x=Temp, y=Signal, group=Sample)) +
  geom_line(aes(color=Sample)) +
  geom_point(size = 1, aes(color=Sample)) +
  scale_color_manual(values = c("Buffer + Dye" = 'black', 'gpV-WT' = 'blue', 'gpV-AA' = 'red', 'gpV-FF' = 'green', 'gpV-Del' = 'purple')) +
  theme_classic() +
  theme(legend.justification =  'top') +
  theme(text = element_text(size = 25)) +
  ylim(75000, 3000000) +
  xlab("Temp") + ylab("Fluorescence")
p1 + theme(legend.title = element_blank())

#Figure 6.b: Calculation mean and sd for plaque count 
#The number of phage plaques were counted and determined the mean and sd

#Read plaque count data file as Stat
Stat <- read.csv("Example-3.csv")

#Assigning each sample with a corresponding variable 
#WT is the wild type phage, whereas AA, FF, and DEL are mutant phage samples
#to be compared to the wild type phage
WT <- Stat$WT
AA <- Stat$AA
FF <- Stat$FF
DEL <- Stat$DEL


#Determined the mean of each samples record phage plaque count
mean(WT)
mean(AA)
mean(FF)
mean(DEL)


#Determined the sd of each samples record phage plaque count
sd(WT)
sd(AA)
sd(FF)
sd(DEL)

#Figure 6.b: data was rearranged to make the data easier to plot using ggplot2
#Read rearranged plaque count data file as plaque
plaque <- read.csv("Example-4.csv")

#Assigning each sample with a corresponding variable 
#WT is the wild type phage, whereas AA, FF, and DEL are mutant phage samples
#to be compared to the wild type phage
Sample <- plaque$Sample

#Assigning the levels for the data frame
Sample <- factor (Sample, levels = c("WT", "AA", "FF", "DEL"))

#Setting up comparisons of the wild type sample verses each mutant
my_comparisons <- list( c("WT", "AA"), c("WT", "FF"), c("WT", "DEL"))

#Setting the plaque count variable as PC
#Not included in this code is the adjust plaque counts based of the amount of 
#phage protein comparison present in Figure 6.a
#See methods section "EOP Assay" for more detail
PC <- plaque$Adjusted.Number.of.Plaques

#Making the data frame for the plaque counts
df <- data.frame(Sample, PC)

# function for computing mean, sd, max and min values for the boxplot
min.mean.sd.max <- function(x) {
  r <- c(min(x), mean(x) - sd(x), mean(x), mean(x) + sd(x), max(x))
  names(r) <- c("ymin", "lower", "middle", "upper", "ymax")
  r
}

#Making the box plot of the phage count with a comparison of wild type phage with each mutant phage
#Statistical significant difference of each group was determine using the stat_summary and stat_compare_means functions below
#Adjusted the line and individual data points to the desired appearance
ggplot(df, aes(x=Sample, y=PC)) + 
  geom_boxplot() +
  stat_summary(fun.data = min.mean.sd.max, geom = "boxplot") +
  stat_compare_means(method = 't.test', comparisons = my_comparisons, label.y = c(70, 80, 90)) +
  geom_jitter(position=position_jitter(width=.2), size=3) + 
  xlab("") + 
  ylab("Number of Plaques 1x10^9 pfu") +
  theme_classic() + 
  theme(text = element_text(size = 25)) + ylim(0,100)
